# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pf1524-ping-prd

on:
  push:
    branches:
      - base
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_64c735ce702d4b159524689832c27e7e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b212bd9531664bdda3ac50626f9c3e00 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_64c735ce702d4b159524689832c27e7e }}/ping:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pf1524-ping-prd'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_22116faf3ba842f1aa2edd5c03b6edea }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_64c735ce702d4b159524689832c27e7e }}/ping:${{ github.sha }}'