name: Building

on:
  push:
    branches: [ "aula" ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: docker login -u acnaweb -p dckr_pat_FgnEIS3MR27b3x8EwXSBN7AnNiM
    - name: build image
      run: docker build -t acnaweb/ping .
    - name: push to docker
      run: docker push acnaweb/ping 
    - uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{AZURE_WEBAPP_PUBLISH_PROFILE}}

