name: Building

on:
  push:
    branches: [ "base" ]
  pull_request:
    branches: [ "base" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env: 
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      REPOSITORY: ping
      
    steps:
    - uses: actions/checkout@v3
    - name: docker login

      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build image
      run: docker build -t ${{secrets.DOCKER_USER}}/$REPOSITORY:$GITHUB_REF_NAME .
    - name: push to registry
      run: docker push ${{secrets.DOCKER_USER}}/$REPOSITORY:$GITHUB_REF_NAME
