name: Building

on:
  push:
    branches: [ "base" ]
  pull_request:
    branches: [ "base" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env: 
        DOCKER_USER: acnaweb
        DOCKER_PASSWORD: dckr_pat_fGfi9GqGC5FQewVcss0I7zq23qI
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build image
      run: docker build -t acnaweb/ping:${{ github.head_ref }}.${{ github.sha }} .
    - name: push to registry
      run: docker push acnaweb/ping:${{ github.head_ref }}.${{ github.sha }}
