name: Building

on:
  push:
    branches: [ "base" ]
  pull_request:
    branches: [ "base" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build image
      run: docker build -t acnaweb/ping:$GITHUB_REF_NAME .
    - name: push to registry
      run: docker push acnaweb/ping:$GITHUB_REF_NAME
